task: classify
batchsz: 50
preproc: 
  mxlen: 100
  rev: false 
  clean: true
backend: pytorch
dataset: SST2
loader: 
  reader_type: default 
unif: 0.25
model: 
  model_type: lstm 
  rnnsz: 100
  dropout: 0.5
  finetune: true
word_embeddings: 
  label: glove-840B
train: 
  epochs: 2
  optim: adam
  eta: 0.001
  model_base: ./models/sst2
  early_stopping_metric: acc


