version: 2
batchsz: 50
modules: [classify_sepcnn]
basedir: sst2-sepcnn-keras
preproc: 
  mxlen: 100
  rev: false
  clean: true
features:
 - name: word
   vectorizer:
     type: token1d
     transform: baseline.lowercase
   embeddings:
     label: w2v-gn
backend: keras
dataset: SST2
loader: 
  reader_type: default
unif: 0.25
model:
  sep: true
  model_type: sepcnn 
  filtsz: 3 
  cmotsz: 100
  dropout: 0.5
  finetune: true
train: 
  epochs: 20 
  optim: adam
  eta: 0.0001
  model_base: ./models/sst2
  early_stopping_metric: acc
  verbose: true


