batchsz: 50
preproc:
    mxlen: -1

backend: tensorflow
dataset: trec
loader:
    reader_type: default

unif: 0.25
model:
    model_type: default
    filtsz: [3]
    dropout: 0.5
    cmotsz: 100

features:
  - name: word
    vectorizer:
      type: token1d
    embeddings:
      label: w2v-gn

  - name: word2
    vectorizer:
      type: token1d
    embeddings:
      label: glove-42B
      transform: baseline.lowercase


train:
    epochs: 30
    optim: adadelta
    eta: 1.0
    model_base: ./models/trec
    early_stopping_metric: acc
    patience: 25
