batchsz: 50
preproc: 
  mxlen: 100
  mxwlen: 40
  rev: false
  clean: true
backend: tensorflow
dataset: SST2
loader: 
  reader_type: default
  do_chars: true
unif: 0.25
model: 
  model_type: default 
  filtsz: [3,4,5]
  cfiltsz: [2,3,4,5,7]
  cmotsz: 100
  char_hsz: 20
  dropout: 0.5
  finetune: true
word_embeddings: 
  label: w2v-gn
charsz: 16 
train: 
  epochs: 2
  optim: adadelta
  eta: 1.0
  model_base: ./models/sst2
  early_stopping_metric: acc


