# This configuration file uses the HuggingFace library via mead-hub
# To run it, do `mead-config --config/conll-bert-hf.yml --embeddings hub:v1:embeddings
#
# To see an example of a BERT configuration that does not require mead-hub
# or HuggingFace dependencies, see `config/conll-bert.yml`
task: tagger
backend: pytorch
conll_output: conll-bert-iobes-hf.conll
unif: 0.1
dataset: conll-iobes

preproc: 
  mxlen: -1
  mxwlen: -1

features:
 - name: word
   vectorizer:
     label: bert-base-cased-dict1d
   embeddings:
     label: bert-base-cased-pytorch
     layers: [-1]

loader:
  reader_type: default
  named_fields: {"0": "text", "-1": "y"}
  label_vectorizer:
    label: y
    type: wordpiece-label-dict1d

model:
  model_type: pass
  constrain_decode: 0
  crf: 0

train:
  batchsz: 32
  epochs: 50
  optim: adam
  eta: 1.0e-5
  patience: 15
  early_stopping_metric: f1
  clip: 5.0
  span_type: iobes 
