task: tagger
backend: pytorch
dataset: wnut-iobes
modules:
 - embed_bert_pytorch
conll_output: wnut-bert.conll
basedir: ./
unif: 0.1
preproc:
  mxlen: -1
  mxwlen: -1
features:
 - name: word
   vectorizer:
     type: wordpiece-dict1d
     embed_file: bert-base-cased
   embeddings:
     type: bert
     dsz: 768
     embed_file: bert-base-cased
     finetune: true
     operator: concat
     layers: [-1]

loader:
  reader_type: default
  named_fields: {"0": "text", "-1": "y"}
  label_vectorizer:
    label: y
    type: wordpiece-label-dict1d
    embed_file: bert-base-cased

model:
  model_type: pass
  constrain_decode: 0
  crf: 0

train:
  epochs: 40
  optim: adam
  eta: 1.0e-5
  early_stopping_metric: f1
  clip: 5.0
  span_type: iobes
  batchsz: 32
