# FIXME
task: tagger
batchsz: 128
conll_output: conllresults.conll
charsz: 50
unif: 0.1
preproc:
  mxlen: -1
  mxwlen: -1
  lower: true
features:
 - name: word
   vectorizer: 
     type: dict1d
     fields: text
     transform: baseline.lowercase
   embeddings: 
     label: glove-6B-100
 - name: char
   vectorizer:
     type: dict2d
   embeddings:
     dsz: 30
     wsz: 30
     type: char-conv
backend: tensorflow
dataset: conll-iobes
loader: 
  reader_type: default
  named_fields: 
    "0": text
    "-1": y
model:
  model_type: default
  wfiltsz: [5]
  cfiltsz: [3]
  hsz: 800
  wsz: 50
  dropout: 0.5
  rnntype: cnn
  layers: 2
  crf: 1
  constrain_decode: true
  activation: relu
train:
  epochs: 600
  optim: sgd
  decay: 0
  eta: 0.001
  mom: 0.9
  patience: 40
  early_stopping_metric: f1
  clip: 5.0
  span_type: iobes
