version: 2
task: classify
basedir: sst2-keras
batchsz: 50
preproc: 
  mxlen: 100
  rev: true 
  clean: true
features: 
 - name: word
   vectorizer: 
     type: token1d
     #transform: baseline.lowercase
   embeddings:
     label: w2v-gn
backend: keras 
dataset: SST2
loader: 
  reader_type: default 
unif: 0.25
model: 
  model_type: nbow 
  hsz: [100, 20]
  dropout: 0.5
  finetune: true
train: 
  epochs: 5 
  optim: adam
  eta: 0.001
  model_base: ./models/sst2
  early_stopping_metric: acc


