batchsz: 50
preproc:
  mxlen: 100
  rev: false
  clean: true
backend: dynet
dataset: SST2
loader:
  reader_type: default
unif: 0.25
model:
  model_type: default
  filtsz: [3,4,5]
  cmotsz: 128
  hsz: 110
  dropout: 0.5
  finetune: true
  layers: 1
word_embeddings:
  label: w2v-gn
train:
  epochs: 2
  optim: adam
  eta: 0.0003
  model_base: ./models/sst2
  early_stopping_metric: acc
