batchsz: 1
preproc:
  mxlen: 100
  rev: false
  clean: true
backend: dynet
dataset: SST2
loader:
  reader_type: default
  trim: true
unif: 0.25
model:
  model_type: nbowmax
  hsz: 256
  dropout: 0.5
  finetune: true
word_embeddings:
  label: w2v-gn
train:
  epochs: 1
  optim: adam
  eta: 0.0003
  model_base: ./models/sst2
  early_stopping_metric: acc
  autobatchsz: 50
