batchsz: 10
preproc:
    mxlen: -1

backend: tensorflow
dataset: trec
loader:
    reader_type: default

unif: 0.25
model:
    model_type: lstm
    hsz: 400
    dropout: 0.5
    layers: 1

word_embeddings:
    label: w2v-gn

train:
    epochs: 30
    optim: adadelta
    eta: 1.0
    model_base: ./models/trec
    early_stopping_metric: macro_f1
    patience: 25