name: Publish to DockerHub 

on:
    push:
        branches:
        - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
              ref: ${{ github.head_ref }}
              token: ${{ secrets.MACHINE_PAT }}
        - name: Build & Push PyTorch CUDA 10 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-pytorch-gpu
              path: docker/Dockerfile.pytorch-cuda10 
              tags: latest

        - name: Build & Push PyTorch CUDA 11 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-pytorch-cuda11
              path: docker/Dockerfile.pytorch-cuda11 
              tags: latest

