name: Publish to DockerHub 

on:
    push:
        branches:
        - 'feature/docker-builds'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build & Push PyTorch CUDA 10 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-pytorch-gpu
              path: docker/Dockerfile.pytorch-cuda10 
              tags: latest

        - name: Build & Push PyTorch CUDA 11 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-pytorch-cuda11
              path: docker/Dockerfile.pytorch-cuda11 
              tags: latest
        - name: Build & Push TF2 CUDA 10 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-tf2-gpu
              path: docker/Dockerfile.tf2-cuda10 
              tags: latest

        - name: Build & Push PyTorch CUDA 11 image
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: meadml/mead2-tf2-cuda11
              path: docker/Dockerfile.tf2-cuda11 
              tags: latest

